default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['HELPDESK_DEV_DB_URL'] %>

test:
  <<: *default
  url: <%= ENV['HELPDESK_TEST_DB_URL'] %>

production:
  <<: *default
  database: helpdesk_production
  username: helpdesk
  password: <%= ENV['HELPDESK_DATABASE_PASSWORD'] %>
